/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import CLASSES.EmployeeManagement;
import CLASSES.EmployeeManagementDAO;
import CLASSES.Themes;
import GUI.Home;
import java.awt.event.KeyEvent;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.regex.*;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;


/**
 *
 * @author Suharsha Wick
 */
public class AddEmployee extends javax.swing.JFrame {

    String currentUser;
   
    /**
     * Creates new form AddEventDetails
     */
    public AddEmployee() {
        Themes theme = new Themes();
        theme.setIcon(this);
        initComponents();               
    }
    public void setCurrentUser(String user){
        currentUser = user;
    }

  //EMAIL-VALIDATION
    private void emailValidation(){
        String Email_PATTERN = "[a-zA-z0-9]{1,20}@[a-zA-z0-9]{1,20}.[a-zA-Z]{2,3}";
        Pattern pattern = Pattern.compile(Email_PATTERN);
        Matcher regexMatcher = pattern.matcher (emp_email.getText());
        if (!regexMatcher.matches())
        {
            JOptionPane.showMessageDialog(null,"E-mail format is incorrect!");
            //emp_errorMsg1.setText("E-mail format is incorrect!");
        }
        else 
        {
            //JOptionPane.showMessageDialog(null,"E-mail format is correct!"); 
        }
    }
    //----------------- end of e-mail validation -----------
    
     //NIC Validation
    private void NIC_Validation(){   
        String NIC_PATTERN = "[0-9]{1,9}[v-x|V-Z]{1}";
        Pattern pattern1 = Pattern.compile(NIC_PATTERN);
        Matcher regexMatcher1 = pattern1.matcher (emp_NIC.getText());
        if (!regexMatcher1.matches())
        {
            JOptionPane.showMessageDialog(null,"NIC format is incorrect!");
            //emp_errorMsg2.setText("NIC  format is incorrect!");
            
        }
        else 
        {
            //JOptionPane.showMessageDialog(null,"NIC format is correct!"); 
        }
    }  
        //--------------- end of NIC validation ----------------
    
    //Image Format
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        emp_FileChooser = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        emp_title = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        emp_jobTitle = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        emp_gender = new javax.swing.JComboBox();
        emp_browse = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        emp_firstName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        emp_middleName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        emp_prefName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        emp_lname = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        emp_age = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        emp_LOS = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        emp_NIC = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        emp_email = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        emp_address = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        emp_cHome = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        emp_cMobile = new javax.swing.JTextField();
        emp_birthdate = new com.toedter.calendar.JDateChooser();
        emp_sDate = new com.toedter.calendar.JDateChooser();
        emp_errorMsg1 = new javax.swing.JLabel();
        emp_nationality = new javax.swing.JComboBox();
        emp_errorMsg2 = new javax.swing.JLabel();
        emp_picCaption = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        emp_accNum = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        emp_accBranch = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        emp_qual_browse = new javax.swing.JButton();
        emp_qual_open = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        emp_qual_eduQual = new javax.swing.JTextArea();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        emp_qual_profQual = new javax.swing.JTextArea();
        emp_qual_cv = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        emp_IC_fname = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        emp_IC_lname = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        emp_IC_relationship = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        emp_IC_contactNumber = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        emp_Add = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Employee");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Title :");

        emp_title.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mr.", "Ms.", "Mrs." }));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Job Title :");

        emp_jobTitle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                emp_jobTitleKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Gender :");

        emp_gender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));

        emp_browse.setText("Browse");
        emp_browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_browseActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("First Name :");

        emp_firstName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                emp_firstNameKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Middle Name :");

        emp_middleName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                emp_middleNameKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Last Name :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Preffered Name :");

        emp_lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_lnameActionPerformed(evt);
            }
        });
        emp_lname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                emp_lnameKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Date of Birth :");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Start Date :");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Age :");

        emp_age.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                emp_ageKeyTyped(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Length of Service :");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Nationality :");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("NIC Number :");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Email :");

        emp_email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                emp_emailKeyTyped(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("Address :");

        emp_address.setColumns(20);
        emp_address.setRows(5);
        emp_address.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                emp_addressKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(emp_address);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("Contact Number (Residence) :");

        emp_cHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_cHomeActionPerformed(evt);
            }
        });
        emp_cHome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                emp_cHomeKeyTyped(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("Contact Number (Mobile) :");

        emp_cMobile.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                emp_cMobileKeyTyped(evt);
            }
        });

        emp_birthdate.setDateFormatString("yyyy-MM-dd");

        emp_sDate.setDateFormatString("yyyy-MM-dd");

        emp_nationality.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sri Lankan", "Indian" }));

        jLabel28.setText("jLabel28");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(797, 797, 797)
                        .addComponent(emp_picCaption, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel13)
                        .addGap(32, 32, 32)
                        .addComponent(emp_NIC, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(emp_cHome, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel15)
                        .addGap(52, 52, 52)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel14))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emp_cMobile, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emp_email, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(emp_errorMsg1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(emp_errorMsg2, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6)))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(emp_middleName, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(492, 492, 492)
                                .addComponent(emp_browse))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(emp_title, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(emp_firstName, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(54, 54, 54)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel3)
                                                    .addComponent(jLabel12)
                                                    .addComponent(jLabel8)
                                                    .addComponent(jLabel10)
                                                    .addComponent(jLabel11)))))
                                    .addComponent(emp_lname, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(81, 81, 81)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(emp_jobTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(emp_gender, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(60, 60, 60)
                                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(emp_nationality, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(emp_birthdate, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(emp_age, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(emp_LOS, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(emp_sDate, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(emp_prefName, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(26, 26, 26))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel1)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel4))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(emp_title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(emp_firstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel2)
                        .addGap(34, 34, 34)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(emp_gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(emp_jobTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(emp_browse))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(emp_middleName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(emp_nationality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emp_picCaption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(emp_lname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8))
                            .addComponent(emp_birthdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(emp_prefName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(emp_age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel9))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(emp_LOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(emp_sDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emp_NIC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emp_cHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel16)))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(emp_cMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(emp_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addGap(26, 26, 26)
                                        .addComponent(jLabel14)))))
                        .addGap(29, 29, 29)
                        .addComponent(emp_errorMsg1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(emp_errorMsg2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel13)))
        );

        jTabbedPane1.addTab("Personal Information", jPanel3);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("Account Number :");

        emp_accNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                emp_accNumKeyTyped(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setText("Bank :");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setText("Branch :");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel20))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(emp_accNum, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                    .addComponent(emp_accBranch))
                .addGap(62, 62, 62)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(240, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(emp_accNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(emp_accBranch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(495, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Bank Account Details", jPanel4);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setText("Curriculum Vitae :");

        emp_qual_browse.setText("Browse");
        emp_qual_browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_qual_browseActionPerformed(evt);
            }
        });

        emp_qual_open.setText("Open");
        emp_qual_open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_qual_openActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setText("Educational Qualifications :");

        emp_qual_eduQual.setColumns(20);
        emp_qual_eduQual.setRows(5);
        jScrollPane2.setViewportView(emp_qual_eduQual);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel23.setText("Proffessional Qualifications :");

        emp_qual_profQual.setColumns(20);
        emp_qual_profQual.setRows(5);
        jScrollPane3.setViewportView(emp_qual_profQual);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel21))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(emp_qual_cv)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(emp_qual_browse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(emp_qual_open)
                .addContainerGap(173, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(emp_qual_browse)
                    .addComponent(emp_qual_open)
                    .addComponent(emp_qual_cv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(135, 135, 135))
        );

        jTabbedPane1.addTab("Qualifications", jPanel5);

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel24.setText("First Name :");

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel25.setText("Last Name :");

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel26.setText("Relationship :");

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel27.setText("Contact Number :");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(emp_IC_contactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addComponent(jLabel24)
                            .addGap(41, 41, 41)
                            .addComponent(emp_IC_fname, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel26)
                                .addComponent(jLabel25))
                            .addGap(31, 31, 31)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(emp_IC_relationship, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(emp_IC_lname)))))
                .addContainerGap(619, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(emp_IC_fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(emp_IC_lname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(emp_IC_relationship, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(emp_IC_contactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(420, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Immediate Contact", jPanel6);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        emp_Add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/add.png"))); // NOI18N
        emp_Add.setText("Add");
        emp_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_AddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(825, Short.MAX_VALUE)
                .addComponent(emp_Add)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(emp_Add)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emp_lnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_lnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emp_lnameActionPerformed

    private void emp_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_AddActionPerformed
         
        emailValidation(); //Validate e-mail
        NIC_Validation();  //Validate NIC
            
        int result = JOptionPane.showConfirmDialog(null,"Are you sure you wish to register new Employee?",null, JOptionPane.YES_NO_OPTION);
        if(result == JOptionPane.YES_OPTION) {
            
        //Read the Employee details
        String title = emp_title.getSelectedItem().toString();
        String job_Title = emp_jobTitle.getText();
        String gender = emp_gender.getSelectedItem().toString();
        String f_Name = emp_firstName.getText();
        String m_Name = emp_middleName.getText();
        String l_Name = emp_lname.getText();
        String prf_Name = emp_prefName.getText();
        
        String LOS = emp_LOS.getText();
        
        String nationality = emp_nationality.getSelectedItem().toString();
        String NIC = emp_NIC.getText();
        String address = emp_address.getText();
        String e_mail = emp_email.getText();
        String c_Home = emp_cHome.getText();
        String c_Mobile = emp_cMobile.getText();
        String acc_Num = emp_accNum.getText();
        String acc_Branch = emp_accBranch.getText();
        String acc_Bank = emp_accBranch.getText();
        String edu_Qual = emp_qual_eduQual.getText();
        String prof_Qual = emp_qual_profQual.getText();
        String emp_rel = emp_IC_relationship.getText();
        String IC_fname = emp_IC_fname.getText();
        String IC_lname = emp_IC_lname.getText();
        String IC_contactNumber = emp_IC_contactNumber.getText();
        String IC_relationship = emp_IC_relationship.getText();
        
        DateFormat currentDate = new SimpleDateFormat("yyyy-MM-dd");
        Date date = new Date();
        String addedDate = currentDate.format(date);
        String DOB = currentDate.format(emp_birthdate.getDate());
        String s_Date = currentDate.format(emp_birthdate.getDate());
        
        String cv_Path = emp_qual_cv.getText();
        String pic_Path = "---";      
              
        String age = "21";
        //Create a EmployeeManagement Object
        EmployeeManagement d = new EmployeeManagement( title,  job_Title,  gender,  f_Name,  m_Name,  l_Name,  prf_Name,  DOB,  s_Date,  age,  LOS,  nationality,  NIC,  address,  e_mail,  c_Home,  c_Mobile,  pic_Path,  acc_Num,  acc_Branch,  acc_Bank,  cv_Path,  edu_Qual,  prof_Qual,  emp_rel,  IC_fname,  IC_lname,  IC_contactNumber, IC_relationship,addedDate,currentUser) ;
        //Save to the database
        EmployeeManagementDAO dao = new EmployeeManagementDAO();
        dao.addEmployee(d);
        
        //Home.loadEmpTable();
        JOptionPane.showMessageDialog(this,"New employee added successfully!","Successful",JOptionPane.INFORMATION_MESSAGE);
        
        
        
        } 
        
    }//GEN-LAST:event_emp_AddActionPerformed

    private void emp_browseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_browseActionPerformed
        JFileChooser emp_FileChooser = new JFileChooser();
        emp_FileChooser.showOpenDialog(null);
        File f = emp_FileChooser.getSelectedFile();
        filename = f.getAbsolutePath();
        
        //String filename1 = f.get();
        emp_picCaption.setText(filename);
        
       
       try {
           File emp_pic = new File (filename);
           FileInputStream fis = new FileInputStream(emp_pic);
           ByteArrayOutputStream bos = new ByteArrayOutputStream();
           byte [] buf = new byte[1024];
           for (int readNum; (readNum = fis.read(buf)) != -1;){
           bos.write(buf,0,readNum);
            }
          person_image = bos.toByteArray();
       }
       catch(Exception e){
           JOptionPane.showMessageDialog(null,e);
       }
    }//GEN-LAST:event_emp_browseActionPerformed

        
    
    private void emp_qual_browseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_qual_browseActionPerformed
        JFileChooser emp_FileChooser = new JFileChooser();
        emp_FileChooser.showOpenDialog(null);
        File file = emp_FileChooser.getSelectedFile();
        String filename = file.getAbsolutePath();
        emp_qual_cv.setText(filename);
    }//GEN-LAST:event_emp_qual_browseActionPerformed

    private void emp_qual_openActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_qual_openActionPerformed
        try{
            
            String query = "SELECT cv_Path FROM Emp_Management ";
        }

        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null,"Error");
        }
    }//GEN-LAST:event_emp_qual_openActionPerformed

    private void emp_cHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_cHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emp_cHomeActionPerformed

    //Interger Validation
    private void emp_cHomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emp_cHomeKeyTyped
        
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c)|| c==10 || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE ))
        {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null,"Invalid Contact Number");
        }
        
    }//GEN-LAST:event_emp_cHomeKeyTyped

    //Interger Validation
    private void emp_cMobileKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emp_cMobileKeyTyped
         char c = evt.getKeyChar();
        if (!(Character.isDigit(c)|| c==10 || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE ))
        {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null,"Invalid Contact Number");
        }
    }//GEN-LAST:event_emp_cMobileKeyTyped

    private void emp_ageKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emp_ageKeyTyped
        
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c)|| c==3 || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE ))
        {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null,"Invalid Age");
        }
    }//GEN-LAST:event_emp_ageKeyTyped

    private void emp_accNumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emp_accNumKeyTyped
        
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c)|| c==16 || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE ))
        {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null,"Invalid Account Number");
        }
    }//GEN-LAST:event_emp_accNumKeyTyped

    private void emp_emailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emp_emailKeyTyped
        
    }//GEN-LAST:event_emp_emailKeyTyped

    private void emp_firstNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emp_firstNameKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isLetter(c)|| (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE ||c==KeyEvent.VK_SPACE))
        {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null,"Invalid Character");
        }
    }//GEN-LAST:event_emp_firstNameKeyTyped

    private void emp_middleNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emp_middleNameKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isLetter(c)|| (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE||c==KeyEvent.VK_SPACE ))
        {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null,"Invalid Character");
        }
    }//GEN-LAST:event_emp_middleNameKeyTyped

    private void emp_lnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emp_lnameKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isLetter(c)|| (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE ||c==KeyEvent.VK_SPACE))
        {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null,"Invalid Character");
        }
    }//GEN-LAST:event_emp_lnameKeyTyped

    private void emp_addressKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emp_addressKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isLetter(c)|| (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE ||c==KeyEvent.VK_SPACE))
        {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null,"Invalid Character");
        }
    }//GEN-LAST:event_emp_addressKeyTyped

    private void emp_jobTitleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emp_jobTitleKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isLetter(c)|| (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE ||c==KeyEvent.VK_SPACE))
        {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null,"Invalid Character");
        }
    }//GEN-LAST:event_emp_jobTitleKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddEmployee().setVisible(true);
            }
        });
    }
    
    //FileInputStream fis;
    private ImageIcon format = null;
    
    //String filename
    String filename = null;
    int s = 0;
    byte [] person_image = null;
    
       
   
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton emp_Add;
    private javax.swing.JFileChooser emp_FileChooser;
    private javax.swing.JTextField emp_IC_contactNumber;
    private javax.swing.JTextField emp_IC_fname;
    private javax.swing.JTextField emp_IC_lname;
    private javax.swing.JTextField emp_IC_relationship;
    private javax.swing.JTextField emp_LOS;
    private javax.swing.JTextField emp_NIC;
    private javax.swing.JTextField emp_accBranch;
    private javax.swing.JTextField emp_accNum;
    private javax.swing.JTextArea emp_address;
    private javax.swing.JTextField emp_age;
    private com.toedter.calendar.JDateChooser emp_birthdate;
    private javax.swing.JButton emp_browse;
    private javax.swing.JTextField emp_cHome;
    private javax.swing.JTextField emp_cMobile;
    private javax.swing.JTextField emp_email;
    private javax.swing.JLabel emp_errorMsg1;
    private javax.swing.JLabel emp_errorMsg2;
    private javax.swing.JTextField emp_firstName;
    private javax.swing.JComboBox emp_gender;
    private javax.swing.JTextField emp_jobTitle;
    private javax.swing.JTextField emp_lname;
    private javax.swing.JTextField emp_middleName;
    private javax.swing.JComboBox emp_nationality;
    private javax.swing.JTextField emp_picCaption;
    private javax.swing.JTextField emp_prefName;
    private javax.swing.JButton emp_qual_browse;
    private javax.swing.JTextField emp_qual_cv;
    private javax.swing.JTextArea emp_qual_eduQual;
    private javax.swing.JButton emp_qual_open;
    private javax.swing.JTextArea emp_qual_profQual;
    private com.toedter.calendar.JDateChooser emp_sDate;
    private javax.swing.JComboBox emp_title;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField14;
    // End of variables declaration//GEN-END:variables
}

